include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: gongjiang/ragflow.dev
    build:
      context: ../
      dockerfile: dev.Dockerfile
    container_name: ragflow.dev
    command: ["bash", "-c", "sleep 1000000000"]
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ../:/code/ragflow
      - ./service_conf.yaml:/code/ragflow/conf/service_conf.yaml
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE}
      - PYTHONPATH=/code/ragflow
    networks:
      - ragflow
    extra_hosts:
      - "raw.githubusercontent.com:185.199.108.133"
    working_dir: /code/ragflow
    restart: always
  
  kibana:
    depends_on:
        es01:
          condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: ragflow-kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - TZ=${TIMEZONE}
    mem_limit: ${MEM_LIMIT}
    networks:
      - ragflow
  
volumes:
  kibanadata:
    driver: local
